# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.ssh.shell="bash"
  config.ssh.forward_agent = true 
  config.ssh.keep_alive = true

  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.provider "virtualbox" do |vb|  
    vb.memory = "2048"
  end

  ssh_pub_key = File.readlines("~/.ssh/vagrant.pub").first.strip
  config.vm.provision "shell", inline: <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys

    apt-get update && apt-get upgrade -y

    apt-get install \
      ca-certificates \
      curl \
      gnupg \
      lsb-release
    
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update && apt-get install docker-ce docker-ce-cli containerd.io -y
  SHELL
end
