# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.ssh.shell="bash"
  config.ssh.forward_agent = true 
  config.ssh.keep_alive = true

  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.provider "virtualbox" do |vb|  
    vb.memory = 2048
    vb.cpus = 1
  end

  config.vm.provision "shell" do |s| 
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/vagrant.pub").first.strip
    s.inline = <<-SHELL 
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys

      sudo apt-get update && sudo apt-get upgrade -y

      sudo apt-get install -y \
      ca-certificates \
      curl \
      gnupg \
      lsb-release
    
      sudo mkdir -p /etc/apt/keyrings
      
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

      sudo chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

      sudo usermod -aG docker vagrant && newgrp docker

      sudo systemctl enable docker.service && sudo systemctl enable containerd.service
  SHELL
  end
end
